TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

EXES = check_wilsonloops_1 check_wilsonloops_2 check_wilsonloops_3 check_wilsonloops_4 check_wilsonloops_5 check_wilsonloops_6 check_wilsonloops_7

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules

