TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

TESTS = check_puregauge_1 check_puregauge_2 check_puregauge_4 check_puregauge_5 check_puregauge_6 check_puregauge_7

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules

