#ifndef PRINT_COMPILER_OPTIONS_H
#define PRINT_COMPILER_OPTIONS_H
#ifdef __cplusplus
    extern "C" {
#endif

// these are defined in the autogenerated cinfo.c
extern char MACROS[];
extern char CI_mkflags[];
extern char CI_cpuinfo[];
extern char CI_linux[];
extern char CI_gcc[];
extern char CI_gitinfo[];
extern char CI_gitrevision[];

void print_compiling_info(void);
void print_compiling_info_short(void);

#ifdef __cplusplus
    }
#endif
#endif