TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

TESTS = check_gauge_covariance check_hermiticity check_gauge_covariance_gpu check_hermiticity_gpu #check_gpu_cpu_identical

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules
