TOPDIR = ../..
MKDIR = $(TOPDIR)/Make


TESTS = check_diracoperator_1 check_diracoperator_1_gpu check_diracoperator_2 check_diracoperator_3 check_diracoperator_3_gpu check_diracoperator_4 check_diracoperator_5 check_diracoperator_6 #speed_test_diracoperator speed_test_diracoperator_flt dirac_test

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules
