var searchData=
[
  ['gamma_5fspinor_2eh_0',['gamma_spinor.h',['../d8/d00/gamma__spinor_8h.html',1,'']]],
  ['geometry_2eh_1',['geometry.h',['../d4/d67/geometry_8h.html',1,'']]],
  ['geometry_5fcheck_2eh_2',['geometry_check.h',['../d4/d3d/geometry__check_8h.html',1,'']]],
  ['geometry_5fdescriptor_2eh_3',['geometry_descriptor.h',['../dc/d56/geometry__descriptor_8h.html',1,'']]],
  ['geometry_5ffuse_2eh_4',['geometry_fuse.h',['../d3/d77/geometry__fuse_8h.html',1,'']]],
  ['geometry_5fgpu_5finit_2eh_5',['geometry_gpu_init.h',['../de/d2e/geometry__gpu__init_8h.html',1,'']]],
  ['geometry_5findexing_2eh_6',['geometry_indexing.h',['../df/d34/geometry__indexing_8h.html',1,'']]],
  ['geometry_5finit_2eh_7',['geometry_init.h',['../d9/d46/geometry__init_8h.html',1,'']]],
  ['geometry_5fmaskstate_2eh_8',['geometry_maskstate.h',['../dd/d37/geometry__maskstate_8h.html',1,'']]],
  ['geometry_5fomp_2eh_9',['geometry_omp.h',['../d6/d76/geometry__omp_8h.html',1,'']]],
  ['geometry_5ftype_2eh_10',['geometry_type.h',['../dc/d95/geometry__type_8h.html',1,'']]],
  ['global_2eh_11',['global.h',['../d2/d49/global_8h.html',1,'']]],
  ['global_5fgpu_2eh_12',['global_gpu.h',['../d4/d44/global__gpu_8h.html',1,'']]],
  ['global_5fsum_2eh_13',['global_sum.h',['../d6/d08/global__sum_8h.html',1,'']]],
  ['gpu_2eh_14',['gpu.h',['../d3/d93/gpu_8h.html',1,'']]],
  ['gpu_5finfo_2ec_15',['gpu_info.c',['../d5/ddc/gpu__info_8c.html',1,'']]],
  ['gpu_5finfo_2eh_16',['gpu_info.h',['../da/dee/gpu__info_8h.html',1,'']]]
];
