TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

TESTS = check_scattering_rhopipi check_scattering_length_I0 check_scattering_length_I2 check_sigma_triangle


LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules
