TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

SRCS = $(wildcard *.c)
GPUFILES = init_gpu.c new_geom_gpu.c geometry_init_gpu.c
LIBNAME = ../libhr.a

#Exclude this source files
EXCLUDE =

include $(MKDIR)/MkRules

