TOPDIR = ..
MKDIR = $(TOPDIR)/Make

EXES = WF_measure WF_measure_adaptative

WF_measure_OBJS = wilsonflow.o
WF_measure_adaptative_OBJS = wilsonflow.o


LIBS += $(TOPDIR)/LibHR/libhr.a


include $(MKDIR)/MkRules

