TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

TESTS = check_gpu_geometry check_format_convert_gpu check_geometry_1 check_geometry_2
FAIL = test_com_speed

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules

