TOPDIR = ..
MKDIR = $(TOPDIR)/Make

EXES = Landau_gaugefix_scalar Coulomb_gaugefix_scalar
 

Landau_gaugefix_scalar_OBJS = gaugefix.o

Coulomb_gaugefix_scalar_OBJS = gaugefix.o


LIBS += $(TOPDIR)/LibHR/libhr.a


include $(MKDIR)/MkRules

