TOPDIR = ..
MKDIR = $(TOPDIR)/Make

SRCS = geometry_SAP.c process_init.c geometry_init.c print_wdmatrix.c test_geometry_mpi.c geometry_mpi_eo.c communications.c communications_flt.c

include $(MKDIR)/MkRules

