TOPDIR = ..
MKDIR = $(TOPDIR)/Make

EXES = scatter_test  main_run main_run_pa just_rho

#scatter_test_OBJS = ../LibHR/Observables/measure_mesons.o ../LibHR/Observables/measure_scattering.o
scatter_test_OBJS = 


LIBS += $(TOPDIR)/LibHR/libhr.a


include $(MKDIR)/MkRules

