TOPDIR = ..
MKDIR = $(TOPDIR)/Make

EXES = scatter_test # main_run

scatter_test_OBJS = ../LibHR/Observables/measure_mesons.o ../LibHR/Observables/measure_scattering.o


LIBS += $(TOPDIR)/LibHR/libhr.a


include $(MKDIR)/MkRules

