TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

TESTS = check_suNg_op check_utils_1 check_utils_4 check_utils_5 check_exp_WF check_clover_exp check_utils_2 check_utils_3 #these are because of glueballs not compiled

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules

