TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

TESTS = check_disc_0 check_disc_1 check_disc_2 check_disc_3 check_disc_4 check_disc_5 

check_disc_0_OBJS = ../../Disconnected/loop_tools.o ../../GaugeFix/gaugefix.o
check_disc_1_OBJS = ../../Disconnected/loop_tools.o ../../GaugeFix/gaugefix.o
check_disc_2_OBJS = ../../Disconnected/loop_tools.o ../../GaugeFix/gaugefix.o
check_disc_3_OBJS = ../../Disconnected/loop_tools.o ../../GaugeFix/gaugefix.o
check_disc_4_OBJS = ../../Disconnected/loop_tools.o ../../GaugeFix/gaugefix.o
check_disc_5_OBJS = ../../Disconnected/loop_tools.o ../../GaugeFix/gaugefix.o

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules
