TOPDIR = ..
MKDIR = $(TOPDIR)/Make

SRCS = linear_algebra.c cg_mshift.c MINRES_mshift.c g5QMR_mshift.c MINRES.c eva.c jacobi.c cg_mshift_flt.c HBiCGstab.c

GPUFILES = linear_algebra.c

#this are not yet updated
# BiCGstab_mshift.c HBiCGstab_mshift.c dirac_eva.c

include $(MKDIR)/MkRules

