TOPDIR = ..

SRCS = linear_algebra.c cg_mshift.c MINRES_mshift.c g5QMR_mshift.c MINRES.c eva.c jacobi.c

#this are not yet updated
# BiCGstab_mshift.c HBiCGstab_mshift.c dirac_eva.c

MKDIR = $(TOPDIR)/Make
include $(MKDIR)/MkRules

