TOPDIR = ..
MKDIR = $(TOPDIR)/Make

SRCS = cg_mshift.c MINRES_mshift.c g5QMR_mshift.c MINRES.c eva.c jacobi.c cg_mshift_flt.c HBiCGstab.c GMRES.c FGMRES.c

GPUFILES = linear_algebra.c TMPL/global_sum_gpu.c

#this are not yet updated
# BiCGstab_mshift.c HBiCGstab_mshift.c dirac_eva.c

include $(MKDIR)/MkRules

