TOPDIR = ..
MKDIR = $(TOPDIR)/Make

EXES = converter_openQCD converter

converter_OBJS = archive_eolexi.o archive_milc.o archive_more_mpieo.o archive_ascii.o archive_fortran.o archive_openQCD.o
converter_openQCD_OBJS = archive_eolexi.o archive_milc.o archive_more_mpieo.o archive_ascii.o archive_fortran.o archive_openQCD.o


LIBS += $(TOPDIR)/LibHR/libhr.a


include $(MKDIR)/MkRules

