TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

SRCS = $(wildcard *.c)
LIBNAME = ../libhr.a

#Exclude this source files
EXCLUDE = trunc_hairpin.c measure_mesons.c measure_baryons.c z2semwall_new.c measure_mesons_ff.c measure_renormalization.c glueballs.c glueballs_op.c z2semwall.c loop_tools.c mesons.c polyakov.c measure_ff.c measure_scattering.c
#Exclude glueballs.c glueballs_op.c
#EXCLUDE = trunc_hairpin.c measure_renormalization.c glueballs.c glueballs_op.c
#EXCLUDE = wilsonloops.c trunc_hairpin.c

include $(MKDIR)/MkRules

