TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

SRCS = $(wildcard *.c)
LIBNAME = ../libhr.a

#Exclude this source files
EXCLUDE = trunc_hairpin.c #glueballs.c glueballs_op.c
#EXCLUDE = trunc_hairpin.c measure_renormalization.c glueballs.c glueballs_op.c
#EXCLUDE = wilsonloops.c trunc_hairpin.c

include $(MKDIR)/MkRules

