TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

SRCS = $(wildcard *.c)
LIBNAME = ../libhr.a

#Exclude this source files
EXCLUDE = trunc_hairpin.c
#EXCLUDE = wilsonloops.c trunc_hairpin.c

include $(MKDIR)/MkRules

