TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

TESTS = check_update_1 check_update_2
FAIL =

check_update_1_OBJS = ../../HMC/hmc_utils.o
check_update_2_OBJS = ../../HMC/hmc_utils.o

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules

