TOPDIR = ..
MKDIR = $(TOPDIR)/Make

SRCS = avr_plaquette.c pta_qprop.c mesons.c g5QMR_trunc.c wilsonloops.c polyakov.c z2semwall.c sf_action.c sf_pcac.c rotated_corrs_gm.c  rotated_corrs_gp.c  rotated_corrs_lm.c  rotated_corrs_lp.c  #trunc_hairpin.c

include $(MKDIR)/MkRules

