TOPDIR = ../..
MKDIR = $(TOPDIR)/Make

EXES = check_rotatedsf_1 check_rotatedsf_2 check_rotatedsf_3 check_rotatedsf_4 check_rotatedsf_5 check_rotatedsf_6 check_rotatedsf_7 check_rotatedsf_8 check_rotatedsf_9 check_rotatedsf_10 check_rotatedsf_11 check_rotatedsf_12

LIBS += $(TOPDIR)/LibHR/libhr.a

include $(MKDIR)/MkRules

