name: build

on:
  push:
    branches:
      - HiRep-CUDA

# cancel previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Ensures that jobs are not cancelled is one job fails
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        nc: [2, 3]
        repr: [FUND, ADJ]
        mpi: [-no-mpi, -mpi]
        ecsw: [-expclover,-no-expclover]
        exclude:
          - nc: 3
            repr: ADJ

    steps:
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: openmpi-bin openmpi-common libopenmpi3 libopenmpi-dev ninja-build
        version: 1.0

    - name: Download HiRep
      run: wget https://github.com/claudiopica/HiRep/archive/${{ github.sha }}.tar.gz && tar -xvf ${{ github.sha }}.tar.gz --strip-components=1
    - name: Configure HiRep
      run: ./Make/write_mkflags.pl -f Make/MkFlags.ini --cc ${{ matrix.compiler }} --env "OMPI_CC=${{ matrix.compiler }}" --mpicc mpicc.openmpi --cflags "-Wall -O1" -n ${{ matrix.nc }} -r ${{ matrix.repr }} ${{ matrix.mpi }} ${{ matrix.ecsw }}
    - name: Build
      run: time ./Make/nj

