name: build-tests

on:
  push:
    branches:
      - HiRep-CUDA

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Ensures that jobs are not cancelled is one job fails
      fail-fast: false
      matrix:
        nc: [2, 3]
        repr: [FUND, ADJ]
        mpi: [-no-mpi, -mpi]
        ecsw: [-expclover,-no-expclover]
        exclude:
          - nc: 3
            repr: ADJ

    name: Build Tests $env:GITHUB_REF_NAME / $env:GITHUB_SHA
    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: openmpi-bin openmpi-common libopenmpi3 ninja-build
        version: 1.0
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - run: ./Make/Utils/write_mkflags.pl -f ./Make/MkFlags.ini -n ${{ matrix.nc }} -r ${{ matrix.repr }} ${{ matrix.mpi }} ${{ matrix.ecsw }}
    - run: ./Make/nj TestProgram
    - run: tar -czf build.tgz build
    - uses: actions/upload-artifact@v3
      with:
        name: build-${{ $env:GITHUB_SHA }}-${{ matrix.mpi }}-${{ matrix.nc }}-${{ matrix.repr }}-${{ matrix.ecsw }}
        path: build.tgz
