name: check-format

on:
  pull_request:
    branches:
      - HiRep-CUDA
  push:
    branches:
      - HiRep-CUDA

# cancel previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: ./.github/actions/install_llvm.sh 17


      - name: Check format with clang-format
        env: 
          CLANG_FORMAT: "clang-format-17"
        run: ./Make/git-hooks-pre-commit -a

