name: ci-gpu

on:
  pull_request:
    branches:
      - HiRep-CUDA
  push:
    branches:
      - HiRep-CUDA

# cancel previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: self-hosted

    steps:
      - name: Download HiRep
        run: wget https://github.com/claudiopica/HiRep/archive/${{ github.sha }}.tar.gz && tar -xvf ${{ github.sha }}.tar.gz --strip-components=1

  
  run-tests:
    runs-on: self-hosted

    strategy:
      # Ensures that jobs are not cancelled is one job fails
      fail-fast: false
      matrix:
        nc: [2, 3]
        repr: [FUND, ADJ]
        omp: [-no-omp, -omp]
        mpi: [-no-mpi, -mpi]
        ecsw: [-expclover,-no-expclover]
        exclude:
          - nc: 3
            repr: ADJ
          - mpi: "-mpi"
            omp: "-omp"
          - omp: "-omp"

    steps:
      - name: Run Tests
        env: 
          OMPI_MCA_mca_base_component_show_load_errors: 0
          CUDA_HPC: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1"
          MPI_HOME: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi4/openmpi-4.0.5"
          NVHPC_CUDA_HOME: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/12.0"
          LD_LIBRARY_PATH: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/12.0/lib:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/compilers/lib:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi4/openmpi-4.0.5/lib::/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/12.0/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/math_libs/lib64"
          CUDA_MATH_LIBS: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/math_libs/12.0"
          OPAL_PREFIX: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/mpi"
          PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi4/openmpi-4.0.5/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/12.0/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/compilers/bin" 
        run: ./TestProgram/run_tests.sh "Algebra DiracOperator Geometry Inverters Sources StoredConfs Utils Propagator Random SpinorField Update WilsonLoops" --no-color --mpicc mpicc --cflags "-Wall -O1" --ldflags "" -n ${{ matrix.nc }} -r ${{ matrix.repr }} ${{ matrix.mpi }} ${{ matrix.omp }} ${{ matrix.ecsw }}

