name: ci-gpu

on:
  pull_request:
    branches:
      - HiRep-CUDA
  push:
    branches:
      - HiRep-CUDA

# cancel previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: self-hosted

    steps:
      - name: create working dir
        run: rm -rf HiRep && mkdir HiRep

      - name: show env
        run: pwd && ls -lah && who am i
      
      - name: Download HiRep
        run: cd HiRep && wget https://github.com/claudiopica/HiRep/archive/${{ github.sha }}.tar.gz && tar -xvf ${{ github.sha }}.tar.gz --strip-components=1

  
  run-tests:
    runs-on: self-hosted
    needs: prepare

    strategy:
      # Ensures that jobs are not cancelled is one job fails
      fail-fast: false
      max-parallel: 1
      matrix:
        nc: [2, 3]
        repr: [FUND, ADJ]
        omp: [-no-omp, -omp]
        mpi: [-no-mpi, -mpi]
        ecsw: [-expclover,-no-expclover]
        exclude:
          - nc: 3
            repr: ADJ
          - omp: "-omp"

    steps:
      - name: Run Tests
        env: 
          OMPI_MCA_mca_base_component_show_load_errors: 0
          CUDA_HPC: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1"
          MPI_HOME: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi4/openmpi-4.0.5"
          NVHPC_CUDA_HOME: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/11.8"
          LD_LIBRARY_PATH: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/11.8/lib:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/compilers/lib:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi4/openmpi-4.0.5/lib::/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/11.8/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/math_libs/lib64"
          CUDA_MATH_LIBS: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/math_libs/11.8"
          OPAL_PREFIX: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/mpi"
          CUDA_INCLUDE: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/11.8/include"
          MPI_INCLUDE: "/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi4/openmpi-4.0.5/include"
          PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/comm_libs/openmpi4/openmpi-4.0.5/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/cuda/11.8/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/23.1/compilers/bin" 
          GITHUB_WORKSPACE: /home/git_runner/actions-runner/_work/HiRep/HiRep/HiRep
        run: export GITHUB_WORKSPACE=/home/git_runner/actions-runner/_work/HiRep/HiRep/HiRep && ./HiRep/TestProgram/run_tests.sh "Algebra DiracOperator Geometry Inverters LinearAlgebra Memory" --gpu --newgeo --fixedstr --no-color --mpicc mpicc --cflags "-Wall -O1" --include "-I${MPI_INCLUDE}  -I${CUDA_INCLUDE} -I${CUDA_MATH_LIBS}/targets/x86_64-linux/include/" --ldflags "-L${MPI_HOME}/lib -L${NVHPC_CUDA_HOME}/lib64 -L${CUDA_HPC}/compilers/lib -L${CUDA_HPC}/math_libs/lib64 -lmpi" -n ${{ matrix.nc }} -r ${{ matrix.repr }} ${{ matrix.mpi }} ${{ matrix.omp }} ${{ matrix.ecsw }}

