name: ci

on:
  pull_request:
    branches:
      - HiRep-CUDA
  push:
    branches:
      - HiRep-CUDA

# cancel previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      # Ensures that jobs are not cancelled is one job fails
      fail-fast: false
      matrix:
        nc: [2, 3]
        repr: [FUND, ADJ]
        mpi: [-no-mpi, -mpi]
        ecsw: [-expclover,-no-expclover]
        exclude:
          - nc: 3
            repr: ADJ

    steps:
      - name: Download HiRep
        run: wget https://github.com/claudiopica/HiRep/archive/${{ github.sha }}.tar.gz && tar -xvf ${{ github.sha }}.tar.gz --strip-components=1

      - name: Check API rate
        uses: ./.github/actions/api-rate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openmpi-bin openmpi-common libopenmpi3 libopenmpi-dev ninja-build
          version: 1.0

      - name: Setup link to mpirun alternative
        run: sudo ln -fs /usr/bin/mpirun.openmpi /usr/bin/mpirun

      - name: Run Tests
        env: 
          OMPI_MCA_mca_base_component_show_load_errors: 0
        run: ./TestProgram/run_tests.sh "Algebra DiracOperator Geometry Inverters Sources StoredConfs Utils Propagator Random SpinorField Update WilsonLoops" --mpicc mpicc.openmpi -cflags "-Wall -O1" -n ${{ matrix.nc }} -r ${{ matrix.repr }} ${{ matrix.mpi }} ${{ matrix.ecsw }}

