name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y graphviz doxygen
          pip install myst==1.0.4 myst_parser==0.18.0 sphinx==5.0.2 sphinxcontrib-bibtex==2.5.0 sphinx-rtd-theme==1.0.0
      - name: Sphinx build
        run: |
          cd Doc && mkdir -p _build/doxygen
          doxygen doxygen/Doxyfile
          sphinx-build . _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/HiRep-CUDA' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Doc/_build/
          force_orphan: true
