name: Docs

on:
  push:
    branches:
      - HiRep-CUDA

# cancel previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y graphviz texlive-base
      - name: Install Doxygen 1.9.4
        uses: engineerd/configurator@v0.0.8
        with:
          name: "doxygen"
          url: "https://github.com/doxygen/doxygen/releases/download/Release_1_9_4/doxygen-1.9.4.linux.bin.tar.gz"
          pathInArchive: "doxygen-1.9.4/bin/doxygen"
      - name: Doxygen build
        run: |
          cd Doc/ && mkdir -p _build/ && doxygen doxygen/Doxyfile
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/HiRep-CUDA' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Doc/_build/html/
          force_orphan: true
