name: mpi-dev

on:
  push:
    branches:
      - HiRep-CUDA

jobs:
  build:

    runs-on: self-hosted
    strategy:
      # Ensures that jobs are not cancelled is one job fails
      fail-fast: false
      matrix:
        nc: [2, 3]
        repr: [FUND, ADJ]
        ecsw: [-expclover,-no-expclover]
        dir: [Algebra,DiracOperator,Geometry,Inverters,Integrators,Mesons,PureGauge,RIMOM,Sources,StoredConfs,Utils,GaugeFix,Propagator,Random,SpinorField,Update,WilsonLoops]
        exclude:
          - nc: 3
            repr: ADJ

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: ./.github/actions/runtests-dev
      with:
        dir: ${{matrix.dir}}
        mpi: -mpi
        nc: ${{ matrix.nc }}
        repr: ${{ matrix.repr }}
        ecsw: ${{ matrix.ecsw }}
